name: Tsubakuro-CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/oltp-sandbox:ubuntu-22.04
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
      volumes:
        - ${{ vars.gradle_cache_dir }}:/root/.gradle
    defaults:
      run:
        shell: bash
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHA_PAT }}

      - name: Assemble
        run: |
          ./gradlew -i clean assemble

      - name: Check
        run: |
          ./gradlew -i check --continue

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
        with:
          junit_input: '**/build/test-results/**/TEST-*.xml'
          junit_test_src_dir: 'src/test/java'
          spotbugs_input: '**/build/reports/spotbugs/main/*.xml'
          checkstyle_input: '**/build/reports/checkstyle/main.xml'

  Publish:
    uses: ./.github/workflows/ci-publish.yml
    if: (contains(github.ref, '/tags/') || contains(github.ref, '/heads/master'))
    needs: Build
    secrets: inherit

  Eisen:
    uses: ./.github/workflows/eisen-integration-test.yml
    if: (github.event.pull_request.draft == false) && (contains(github.ref, '/tags/') || contains(github.ref, '/pull/') || contains(github.ref, '/heads/master'))
    needs: Build
    secrets: inherit

  Iceaxe:
    uses: project-tsurugi/eisen/.github/workflows/iceaxe-dbtest-ipc.yml@master
    if: (github.event.pull_request.draft == false) && (contains(github.ref, '/tags/') || contains(github.ref, '/pull/') || contains(github.ref, '/heads/master'))
    needs: Build
    secrets: inherit
    with:
      job_name: 'Iceaxe / Test'
